### ISSUE TITLE
Re:  It would be nice to be able to pin a floating window #102 

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#108]
Hi Sergio,
regarding Ticket #102 

What I meant was the following:
![pinning](https://user-images.githubusercontent.com/11087133/100239144-56bc0e00-2f31-11eb-8379-8c48a1d536ce.gif)

Basically if you have alot of floating windows it would be good, from a user perspective, to be able to 'pin' several of them, meaning be able to decide that some have to stay in front for now.
This also would be nice to do programatically.

The following code is a mockup of this behaviour:

```
#include <QtWidgets>
#include <QPushButton>
#include <QHBoxLayout>


QVector<QWidget*> vec;
void bringFloatingToFront()
{
    for(auto& w: vec)
    {
        w->raise();
    }
}

int main(int argc, char **argv)
{
    QApplication app(argc, argv);

    QWidget mainWindow;
    mainWindow.setWindowTitle("MainWindow");

    auto layout = new QHBoxLayout(&mainWindow);

    auto float_to_front_btn = new QPushButton("Float to front");
    auto main_to_front_btn = new QPushButton("Main to front");

    layout->addWidget(float_to_front_btn);
    layout->addWidget(main_to_front_btn);

    QObject::connect(float_to_front_btn, &QPushButton::clicked, &bringFloatingToFront);
    QObject::connect(main_to_front_btn, &QPushButton::clicked, [&]{mainWindow.raise();});


    for(int i =0 ; i<5; ++i)
    {
        auto w = new QWidget(nullptr, Qt::Tool);
        auto float_layout = new QHBoxLayout(w);

        auto pin_btn = new QPushButton("Pin");
        pin_btn->setCheckable(true);
        float_layout->addWidget(pin_btn);

        QObject::connect(pin_btn, &QPushButton::clicked, [w, pin_btn]{w->setWindowFlag(Qt::WindowStaysOnTopHint, pin_btn->isChecked()); w->show();});

        vec << w;
    }

    int cnt = 0;
    for(auto& w : vec)
    {
        auto geo = w->geometry();
        geo.setX(0 + cnt * 50);
        geo.setY(0+ cnt* 50);
        geo.setWidth(500);
        geo.setHeight(500);
        ++cnt;
        w->setGeometry(geo);
        w->show();
    }

    mainWindow.resize(500, 500);
    mainWindow.move(0+ cnt*50, 0+cnt*100);
    mainWindow.show();
    mainWindow.raise();


    return app.exec();
}
```

**Comment by ferdnyc** [comment]
Random peanut-gallery suggestion: I wouldn't use "Pin" to refer to this feature/action. (Just because there's already a pin _icon_ in KDDW titlebars, and it does something completely different. Overloading it to mean one thing for docked windows, and a different thing for floating windows, seems... confusing.) 

There's already a feature in many window managers for this, usually called "Always on top". Not to be confused with "Always on visible workspace"/"Visible on all desktops" (only applicable when windows are arranged over multiple virtual screens), a feature that is often represented by a pin icon.
