### ISSUE TITLE
Request: Create floating windows sooner

### ISSUE THREAD

**Issue by pklaffert** [KDAB/KDDockWidgets#117]
In our application we have a use case to put dock windows into a QGraphicsScene. A graphcisscene only accepts toplevel windows. But the floating window gets only created in the show event of the dock widget. So we have to show the dockwidget before we can put it into the scene. This leads often to ugly flicker effects.

Is there a reason that the floating window only gets created in the show event?

**Comment by iamsergio** [comment]
Creating the FloatingWindow immediately would mean creating unneeded temporary windows when you'd immediately dock the dock widget

**Comment by pklaffert** [comment]
I was thinking the same. But we open most of our widgets floating so that the user than can do with them what he wants. So it would be at least nice if there would be an option to choose whether floating windows are created immediately or on show.

**Comment by iamsergio** [comment]
So you want the FloatingWindow, but with it having visible=false ?

**Comment by pklaffert** [comment]
I want it to be accessible as soon as the dockwidget is created.

**Comment by iamsergio** [comment]
yes, but can the FloatingWindow have visible=true, as soon as the dock widget is created ?

**Comment by pklaffert** [comment]
visibility is only needed at show. A hidden dockwidget does not need a visible floating window.

**Comment by iamsergio** [comment]
That what you ask is exactly the same as doing currently:

```
auto dw = new DockWidget();
dw->show(); // Creates the FloatingWindow
```

If I add the special API so that DockWidget constructor creates the FloatingWindow inside, it will have the same result.
If you see flicker with the 1st approach then you'll also see flicker with the 2nd approach, because the only difference is moving code to another place.

You'll type one line less, but the CTOR will do 1 more line internally.

**Comment by pklaffert** [comment]
Ok, I try to explain it with code:
What I want, is to put a complete dockwidget, including the floating window, into a graphicsscene. But since the floating window only gets created on show I have to make it visible before I can put it into the scene. That creates a flickering.
```
auto scene = new QGraphicsScene();
  auto view = new QGraphicsView();
  view->setScene(scene);
  view->setWindowTitle(QStringLiteral("GraphicsScene"));
  view->show();

  auto widget = newMyWidget();
  auto dw = new KDDockWidgets::DockWidget(QStringLiteral("dock in scene"));
  dw->setWidget(widget);
```
...
`scene->addWidget(dw); // -> does put the dockwidget into the scene but has a stray floating window outside`

...
`scene->addWidget(dw->window()); -> same as above`

...

```
dw->show();
scene->addWidget(dw->window()) // -> does work but flickers;
```

**Comment by iamsergio** [comment]
I understand that it flickers, but I don't see a solution.
Embedding anything that creates a top-level window will flicker, even if you immediately embed it.

FloatingWindow is always created with a native QWindow backing it up, if you embed it that it will flicker due to that QWindow.

Anyway, KDDW has lots of places assuming that FloatingWindow is not embedded, including Win32 native API.

The whole concept of "Floating" requires "top-level".
