### ISSUE TITLE
Question: Tips on styling titlebar?

### ISSUE THREAD

**Issue by gnuherdnix** [KDAB/KDDockWidgets#146]
Hi @iamsergio thanks very much for all of your work on this project. 

In your [Desktop Days video](https://www.youtube.com/watch?v=Ty_6dqzq0s0) you mention the ability to style the dock widgets, but I am having a difficult time figuring out how to style the title bar from QSS. Would you mind sharing any tips?

I found the example code that shows how to customize the titlebar, but I am looking to remove the rounded border and frame that is showing on macOS. 
<img width="352" alt="Screen Shot 2021-01-23 at 8 30 18 PM" src="https://user-images.githubusercontent.com/76967970/105618839-ea874a80-5db9-11eb-9153-1408f9441d17.png">

**Comment by iamsergio** [comment]
KDDW doesn't do anything explicit to support QSS.
QSS is supported by Qt for any QWidget that doesn't override paintEvent() (or for those which overrides paintEvent() properly).
Meaning KDDW supports QSS because it simply inherits that feature from Qt.

I've added Config::setDisabledPaintEvents() in case you need to disable some paintEvent(), so that it doesn't block QSS.

Anyway, QSS is frowned upon and discouraged usually. The prefered way is to inherit from the internal widgets and implement
the paintEvent yourself().

See also FrameWidget::paintEvent() and FloatingWindow::paintEvent() which might be the source of the round corners.
The other source might be QTabWidget::paintEvent()
