### ISSUE TITLE
The size of a sizebar widget won't be saved and loaded

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#155]
Code basis: 1.2.1 -> (2021-01-28)
Steps to reproduce:
* Enable the auto-hide feature
* Pin a widget into the sidebar
* Show the sidebar widget
* Change the size
* Hide the sidebar widget and show it again
* Oberserve that the size is still default
* Wish/Expectation: The current size of the sidebar widegt should be saved and loaded
* Compare this to the dock/undock feature -> If you dock an widget the size will be laoded
Here is an animation for better understanding:
![size_behaviour_of_sidebar_widget](https://user-images.githubusercontent.com/3143027/106467883-8a6d6400-649d-11eb-90bc-2308a075131d.gif)

**Comment by tlaemmlein** [comment]
Here is an example which demonstrates the problem with an program editor:
![example_of_not_stored_sidebar_window_size](https://user-images.githubusercontent.com/3143027/106720153-6461d400-6603-11eb-88a8-98872c676e22.gif)

**Comment by tlaemmlein** [comment]
@iamsergio Thanks, but please merge the changes into the 1.2 branch.

**Comment by iamsergio** [comment]
v1.3.0 and v1.2.1 were released. This change is included in v1.3.0.  Branch `1.2` is now closed.

I'm not very fond of adding "unimplemented features" to the stable branch. Will rather just add pure bug fixes or any other critical issues, since now many projects are using stable, so things get a bit more strict.

On the upside, the delta to 1.3 is very small, so should be an easy and uneventful update.
