### ISSUE TITLE
Restoring of Tabs order

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#165]
1. Run example "kddockwidgets_example";
2. Tabify at MainWindow "DockWidget #0", "DockWidget #<span/>1", "DockWidget #<span/>2" 
![image](https://user-images.githubusercontent.com/7323010/107363731-fd0cbe00-6af3-11eb-9258-56d187ff765e.png)
3. Undock by mouse "DockWidget #<span/>1";
4. Undock by mouse "DockWidget #<span/>2";
5. Dock "DockWidget #<span/>1";
6. Dock "DockWidget #<span/>2";

You can see that the order of tabs is **different**: 
![image](https://user-images.githubusercontent.com/7323010/107363968-4bba5800-6af4-11eb-9035-cf7727862b8c.png)

Is it possible to modify this behavior?
P.S.:  `QDockWidget` support "correct" order of tabs-restoring.

Environment:
1. Windows 10 (64bit);
2. Qt 5.15.1 MSVC 2019 64bit;
3. KDDW 1.1-1.3.

**Comment by iamsergio** [comment]
I think so

**Comment by iamsergio** [comment]
It's a bit of a pickle, Dock2 only remembers it was at index 1

**Comment by bbc131** [comment]
With the current version, I cannot reproduce @amuralev s issue.
The current functionality seems always to append the inserted dock to the end, which is why I end up with the desired order of 0, 1, 2 if I follow the description of @amuralev.

**But I have the following question:**
What if I have a specific order, which should always be obeyed. 
With the example above (DockWidgets `#0`, `#1` and `#2`), this would mean, if some of them are tabbed together `#0` is always before `#1` and `#2`. And `#1` is always before `#2`.
So for example, there could be `#0`, `#2` tabbed, but never `#2`, `#0`.

Is there a possibility to achieve this without touching the KDDockWidgets internals?
(The information for the order could be in the `uniqueName`.)

**Comment by iamsergio** [comment]
You can now pass a lambda and change the tabIndex before it's used.
