### ISSUE TITLE
Bug about dragging dockwidget by mouse

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#166]
No exact steps for reproducing... 
But for me they are:
1. Run example "kddockwidgets_example";
2. Undock "DockWidget #0" by "**very small**" drag-distance (in top direction of monitor);

It seems that drag-operation is **NOT** finished.
![system_dragging_bug](https://user-images.githubusercontent.com/7323010/107373924-7ad6c680-6b00-11eb-9915-ec90c2ad795a.gif)

Environment:
1. Windows 10 (64bit);
2. Qt 5.15.1 MSVC 2019 64bit;
3. KDDW 1.3 (latest release, tag v1.3.0).

P.S.: Failed to reproduce with commenting system-depended code block 
![image](https://user-images.githubusercontent.com/7323010/107374355-ee78d380-6b00-11eb-8648-772a77cc1033.png)

**Comment by iamsergio** [comment]
investigating

**Comment by iamsergio** [comment]
reproduced

**Comment by liszto** [comment]
Hello ! 
I'm using Qt 5.14 + Windows 10 + KDDockWidget 1.5 and I'm currently facing the opposite issue 
When I release my mouse above the drop indicator, sometimes it matches with the lambda check (every 100ms) and I supposed the mouse left button state between Qt & Window is not the same just at this particular moment and it fails to dock whereas the click release is on an indicator.
If I click and release without moving at the same place it will dock.

I try to comment the code used for the this bugfix (166) and the issue seems gone (I say seems because it's not 100% reproduced) and without the code I can't reproduced the bug mentioned above.
