### ISSUE TITLE
Usage of Qt::WindowShortcut context with KDDW

### ISSUE THREAD

**Issue by amuralev** [KDAB/KDDockWidgets#169]
It's necessary to apply [patch.txt](https://github.com/KDAB/KDDockWidgets/files/6027310/patch.txt).

1. Run "kddockwidgets_minimal_example";
2. Activate **MainWindow** Window;
3. Press key "S";
4. See output window (something like _auto __cdecl main::<lambda_38977334283a8c0a4eb099fed086f779>::operator ()(void) const ": action triggered"_);
5. Activate any **FLOAT** dock window;
6. Press key "S";
7. See output... **ACTION NOT TRIGGERED**!

`QDockWidget` use `Qt::Tool` as window flag for floating state and takes place code from "private" part of Qt: 
![image](https://user-images.githubusercontent.com/7323010/108815335-b7f58b00-75cd-11eb-8b13-487e27e3762b.png)

Will this behavior be fixed?

P.S.: The ability to change the window flag has been added by [cde814b21](https://github.com/KDAB/KDDockWidgets/commit/cde814b216ad27658c4a477158e0045e44a3e7aa), BUT **title rendering artifacts EXIST** with no option `KDDockWidgets::Config::Flag_NativeTitleBar`.

Environment:

1. Windows 10 (64bit);
2. Qt 5.15.1 MSVC 2019 64bit;
3. KDDW 1.3 (tag v1.3.0).

**Comment by iamsergio** [comment]
Before looking into Qt sources, let's define requirements and expectations.

Qt's documentation for `Qt::WindowShortcut`  says `The shortcut is active when its parent widget is a logical subwidget of the active top-level window.` Since a floating widget is a top-level, it's expected that the action isn't triggered.

QDW doesn't seem to honour this and has a workaround for Qt::Tool as you mention.

A clean solution I think would be a new enumerator in `Qt::ShortcutContext`, so user could explicitly say if he wanted the parent window to be included in the shortcut context.

KDDW doesn't use `Qt::Tool` on Windows as aero-snap wouldn't work.

Have you tried both setting Flag_NativeTitleBar and Qt::Tool ?

**Comment by amuralev** [comment]
Thanks for the feedback!
The problem is that we have quite a lot of code depending on the `QDockWidget`+shortcuts (we would like to keep the existing behavior by switching to KDDW against Windows Aero Snap)...
Yes, we tried `KDDockWidgets::Config::Flag_NativeTitleBar` and `Qt::Tool` --> we got some little bugs

1. https://github.com/KDAB/KDDockWidgets/issues/170 (already closed at this moment);
2. Not working "Double clicks" on native titlebar (most likely easy enough to solve)...

So, are there any other reasons for that KDDW do not use `Qt::Tool` (except for non-working aero-snap)?

**Comment by iamsergio** [comment]
yes, it's just the aero-snap.

If double-clicking on Qt::Tool+QDW was working then we can fix it for KDDW too.

An alternative is catching the QShortcut events with an event filter and forwarding them to your main window.

**Comment by amuralev** [comment]
I think it (`Qt::Tool` + double clicks + native titlebar) would be useful for some cases. Do we need to create a separate task for this?

**Comment by iamsergio** [comment]
yes, but please test if normal QDW supports double click to maximize, might be a Windows limitation
