### ISSUE TITLE
Need color  theming for side bar

### ISSUE THREAD

**Issue by tlaemmlein** [KDAB/KDDockWidgets#172]
Code base: 1.3.1
Our application use theming (dark and light mode). By switching to the dark mode the color text in the sidebar doesn't change. It remains black. See the animation for more details:
![color_theming_side_bar](https://user-images.githubusercontent.com/3143027/109125581-848d3a80-774c-11eb-9163-d2941ff2353e.gif)
Furthermore the line under the side bar text is blue, but we have this color defined to kind of orange.

Greetings,
Thomas

**Comment by tlaemmlein** [comment]
@iamsergio Do you have time to take care of this ticket?

**Comment by iamsergio** [comment]
I can't integrate your patch if you haven't signed the CLA document for copyright transfer.
(Because we need to be able to dual-license KDDW, otherwise this part would be GPL only)

But I'll ask a colleague to fix this without looking, and he'll probably reach the same fix, as this is quite trivial.
Meanwhile you can also sign the CLA, it's just for our protection and you don't loose any rights.

**Comment by tlaemmlein** [comment]
There is no patch. So you can implement your own solution.
