### ISSUE TITLE
Layout not working with different monitor scaling

### ISSUE THREAD

**Issue by narnaud** [KDAB/KDDockWidgets#38]
* Start a program on a screen with a scaling set at 125%
* Move to another screen with scaling set at 100%: the application is unusable
* Resize the application: the layout is destroyed
* Move the application back to the first screen: it works again

**Comment by iamsergio** [comment]
Is this on Windows ?

**Comment by narnaud** [comment]
It's a feedback from somebody else, so I can't know for sure.

**Comment by iamsergio** [comment]
I've tested on my Windows 10 and I can't reproduce.

To procede, let's make sure:

1) You have the latest KDDW (git pull in master branch)

2) The problem is reproducible with the shipped example (kddockwidgets/examples/dockwidgets). Which makes it easier for me to debug. If it's repro only in your app then I'll need a minimal testcase.

3) Which Qt version are you on ? I've tested this bug against Qt 5.14.0.

4) Did you use any other HDPI options ? like Qt::AA_EnableHighDpiScaling, env variables, etc.

5) What's the size of each screen and is it nvidia/Intel GPU ? (longshot but I've seen weird bugs with Intel once)

**Comment by pklaffert** [comment]
I could reproduce the following way:
1. using latest master
2. it is reproducible if you force the use of native windows
  - for that I called winId() in the mainwindow and in the widget class
3. could only reproduce with Qt5.12.5, with Qt5.14 and 5.15rc2 there was no problem
4. no change in the KDDW example
5. - primary monitor laptop with 1920 x 1080 and 175% desktop scaling
    - secondary monitor 3440 x 1440 and 100% desktop scaling
    - nvidia card

To reproduce:
Start Example on primary monitor and drag to secondary. You'll immediately see the effect ( as seen on screenshot )
![kddw](https://user-images.githubusercontent.com/11087133/82438294-19198c80-9a99-11ea-8bef-5cfbe44cf3dd.png)

**Comment by iamsergio** [comment]
reproduced, thanks for the detailed steps

**Comment by iamsergio** [comment]
This is not a KDDW bug and can even be reproduced with a minimal Qt application consisting of a single button calling winId().

I've opened https://bugreports.qt.io/browse/QTBUG-84386 and attached a test-case.
