### ISSUE TITLE
Status of QtQuick implementation?

### ISSUE THREAD

**Issue by robertfellinger** [KDAB/KDDockWidgets#49]
Apologies if this is the wrong place, but just generally curious about the status of using this in a QtQuick-based project? I see many references to it across the source files, but note that it is still part of the 'Roadmap' at the same time. It seems like it is not quite functional yet, but please correct me if I'm wrong. 

Assuming there is still work to be done, is there any particular way to be helpful in terms of contributions?

**Comment by iamsergio** [comment]
The QtQuick ported was halted while the "layouting engine" was being rewriten (code in multisplitter), that took a lot of time, but it's done now.

I'm now finishing max-size constraint support and QtQuick is next in my list.

The multisplitter layout is already ready for QtQuick, and you can try with:
-DOPTION_DEVELOPER_MODE=ON -DBUILD_MULTISPLITTER_QTQUICK_FRONTEND=ON
(click the indicators).

Now need to do the same for the other classes.
There's a bunch of "Quick" leftovers from a previous experience, that's to be removed.

Let's see how it goes :)

**Comment by robertfellinger** [comment]
Thank you for the update! Really looking forward to being able to leverage this in QtQuick. Again, let me know if I can contribute even in some small way...

**Comment by ruilvo** [comment]
Hey, 
Dropping in to ask for an update to this question!
Also, as a P.S., do you think this will work nicely with Qt6, QML on Qt6 and work fine with the new rendering engine stuff?

**Comment by iamsergio** [comment]
Been busy making the 200 tests build when compiled for QtQuick, that's done now.
Next step is actually making them pass. I think about 130 pass right now. 
The remaining 70 are either due to bugs in the tests themselves or bugs in the KDDW QtQuick implementation, or simply core functionality I haven't ported yet.
Then there's styling missing.

I think we're on track for a December release with QtQuick support.

The new RHI Qt6 stuff shouldn't affect KDDW, It will probably be just a recompile.

**Comment by ruilvo** [comment]
Thanks for the update Sergio! I'm looking forward to all of this! Thanks, and great work!
