### ISSUE TITLE
Unexpected resize of the docked widgets. Follow up for #84

### ISSUE THREAD

**Issue by nandishnan4** [KDAB/KDDockWidgets#97]
Hi Sergio,

we still find certain unexpected resizing behavior from KDAB docking framework. 
When we have 3 widgets docked on the MainWindow, floating and re-docking of one widget increases the size of the widget which was never touched. 
Please have a look at the giff for better explanation.

![UnexpectedResizeOfWidgets](https://user-images.githubusercontent.com/8441461/98960038-312c0f00-2504-11eb-98d9-4443236ee3c7.gif)

I have stacked the widgets next to each other, it is the same issue if the widgets are stacked on top of each other.

Kind Regards
Nandish

**Comment by iamsergio** [comment]
I understand it looks weird, but it's a rule by design.
You can help come up with a better rule though.

The generic rule is that when you add the 3rd widget to a layout, all existing docked widgets will contribute and shrink, to make space for the new one.

We could say "only the immediate neighbor should contribute", but then some people might complain that the middle dock widget is getting squeezed too much.
